export default {
  container: {
    flex: 1,
    backgroundColor: "#0a0a12",
  },
  safeArea: {
    flex: 1,
  },
  gradient: {
    flex: 1,
  },

  // Home / Record screen
  homeContainer: {
    flex: 1,
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingTop: 50,
    paddingBottom: 30,
    backgroundColor: "#0a0a12",
  },
  logoContainer: {
    alignItems: "center",
    marginTop: 10,
  },
  logo: {
    fontSize: 46,
    fontWeight: "900",
    color: "#A855F7",
    letterSpacing: 4,
    textShadowColor: "rgba(168, 85, 247, 0.5)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 20,
  },
  tagline: {
    fontSize: 13,
    color: "#7C3AED",
    marginTop: 6,
    letterSpacing: 3,
    fontWeight: "600",
  },
  recordSection: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
  },
  recordButton: {
    width: 170,
    height: 170,
    borderRadius: 85,
    borderWidth: 4,
    borderColor: "#A855F7",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#A855F7",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 30,
    elevation: 20,
  },
  recordButtonInner: {
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: "#7C3AED",
    justifyContent: "center",
    alignItems: "center",
  },
  recordButtonRecording: {
    width: 170,
    height: 170,
    borderRadius: 85,
    borderWidth: 4,
    borderColor: "#F43F5E",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#F43F5E",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 30,
  },
  recordButtonInnerRecording: {
    width: 70,
    height: 70,
    borderRadius: 14,
    backgroundColor: "#F43F5E",
  },
  recordLabel: {
    color: "#A855F7",
    fontSize: 16,
    fontWeight: "800",
    letterSpacing: 2,
  },
  recordLabelRecording: {
    color: "#F43F5E",
    fontSize: 14,
    fontWeight: "700",
    marginTop: 16,
    letterSpacing: 1,
  },
  timerText: {
    color: "#06B6D4",
    fontSize: 34,
    fontWeight: "300",
    fontFamily: "monospace",
    marginTop: 20,
    textAlign: "center",
    textShadowColor: "rgba(6, 182, 212, 0.3)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  optionsRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 10,
  },
  optionButton: {
    alignItems: "center",
    padding: 14,
  },
  optionIcon: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: "rgba(168, 85, 247, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(168, 85, 247, 0.2)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
  },
  optionLabel: {
    color: "#9CA3AF",
    fontSize: 11,
    fontWeight: "600",
  },

  // Processing screen
  processingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
    backgroundColor: "#0a0a12",
  },
  processingTitle: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "800",
    marginTop: 30,
  },
  processingSubtitle: {
    color: "#6B7280",
    fontSize: 14,
    marginTop: 10,
    textAlign: "center",
  },
  processingSteps: {
    marginTop: 40,
    width: "100%",
    gap: 14,
  },
  stepRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: "rgba(168, 85, 247, 0.06)",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(168, 85, 247, 0.1)",
  },
  stepRowActive: {
    backgroundColor: "rgba(168, 85, 247, 0.12)",
    borderColor: "#A855F7",
  },
  stepRowDone: {
    backgroundColor: "rgba(34, 197, 94, 0.08)",
    borderColor: "rgba(34, 197, 94, 0.3)",
  },
  stepIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "rgba(168, 85, 247, 0.15)",
    justifyContent: "center",
    alignItems: "center",
  },
  stepText: {
    color: "#6B7280",
    fontSize: 14,
    fontWeight: "600",
    flex: 1,
  },
  stepTextActive: {
    color: "#A855F7",
  },
  stepTextDone: {
    color: "#22C55E",
  },

  // Results screen
  resultsContainer: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 50,
    backgroundColor: "#0a0a12",
  },
  resultsTitle: {
    color: "#fff",
    fontSize: 24,
    fontWeight: "800",
    textAlign: "center",
  },
  resultsSubtitle: {
    color: "#6B7280",
    fontSize: 13,
    textAlign: "center",
    marginTop: 6,
  },
  keyBadge: {
    alignSelf: "center",
    backgroundColor: "rgba(168, 85, 247, 0.2)",
    borderWidth: 1,
    borderColor: "#A855F7",
    paddingHorizontal: 18,
    paddingVertical: 7,
    borderRadius: 20,
    marginTop: 14,
  },
  keyBadgeText: {
    color: "#A855F7",
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 1,
  },
  playerCard: {
    backgroundColor: "rgba(168, 85, 247, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(168, 85, 247, 0.15)",
    borderRadius: 22,
    padding: 22,
    marginTop: 24,
  },
  playerTitle: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  playerSubtitle: {
    color: "#6B7280",
    fontSize: 12,
    marginTop: 2,
  },
  playButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#A855F7",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 16,
    alignSelf: "center",
    shadowColor: "#A855F7",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 15,
  },
  progressBar: {
    height: 4,
    backgroundColor: "rgba(168, 85, 247, 0.15)",
    borderRadius: 2,
    marginTop: 16,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#A855F7",
    borderRadius: 2,
  },
  timeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
  },
  timeText: {
    color: "#6B7280",
    fontSize: 11,
    fontFamily: "monospace",
  },
  downloadButton: {
    backgroundColor: "rgba(6, 182, 212, 0.15)",
    borderWidth: 1,
    borderColor: "#06B6D4",
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 20,
  },
  downloadButtonText: {
    color: "#06B6D4",
    fontSize: 16,
    fontWeight: "700",
  },
  retakeButton: {
    alignItems: "center",
    marginTop: 16,
    paddingVertical: 12,
  },
  retakeText: {
    color: "#6B7280",
    fontSize: 14,
    fontWeight: "600",
  },

  // Settings / Options
  settingsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(168, 85, 247, 0.08)",
  },
  settingsLabel: {
    color: "#9CA3AF",
    fontSize: 14,
    fontWeight: "600",
  },
  settingsValue: {
    color: "#A855F7",
    fontSize: 14,
    fontWeight: "700",
  },

  // Waveform
  waveformContainer: {
    height: 80,
    backgroundColor: "rgba(168, 85, 247, 0.06)",
    borderWidth: 1,
    borderColor: "rgba(168, 85, 247, 0.12)",
    borderRadius: 14,
    overflow: "hidden",
    marginVertical: 16,
  },
  waveform: {
    flex: 1,
  },

  // Bottom tab
  tabBar: {
    backgroundColor: "#0a0a12",
    borderTopWidth: 0,
    height: 70,
    paddingBottom: 10,
    paddingTop: 6,
  },
  tabLabel: {
    fontSize: 10,
    fontWeight: "600",
  },
};
